<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="DESKTOP-JC2HQ9T" name="com.test.LoginTest" tests="6" failures="1" timestamp="11 Mar 2020 19:18:14 GMT" time="55.057" errors="0">
  <testcase name="AddVariants" time="8.407" classname="com.test.LoginTest"/>
  <testcase name="AddVariants" time="8.292" classname="com.test.LoginTest"/>
  <testcase name="AddVariants" time="8.608" classname="com.test.LoginTest"/>
  <testcase name="AddVariants" time="8.300" classname="com.test.LoginTest"/>
  <testcase name="checkErrorMessageForEmail" time="9.383" classname="com.test.LoginTest"/>
  <testcase name="checkErrorMessageForPassword" time="12.067" classname="com.test.LoginTest">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	expected [Please enters password 123456] but found [Please enter password 123456]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [Please enters password 123456] but found [Please enter password 123456]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
at com.Util.Utility.assertAll(Utility.java:79)
at com.test.LoginTest.checkErrorMessageForPassword(LoginTest.java:64)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
    </failure>
  </testcase> <!-- checkErrorMessageForPassword -->
</testsuite> <!-- com.test.LoginTest -->
